services:
  - type: web
    name: CropSense-AI
    env: python
    plan: free
    branch: main
    region: oregon
    buildCommand: pip install -r final_build/requirements.txt
    startCommand: python final_build/app.py
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
    autoDeploy: true
