services:
  - type: web
    name: CropSense-AI
    env: python
    plan: free
    branch: main
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT final_build.wsgi:application
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
    autoDeploy: true
